# Generated by Django 5.0.6 on 2026-06-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrobeca',
            name='valor',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Valor'),
        ),
    ]
