# Generated by Django 5.0.6 on 2026-06-05 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convocatorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Cédula de identidad')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('datos_completos', models.BooleanField(default=False, verbose_name='Datos completos')),
                ('convocatoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulantes', to='convocatorias.convocatoria', verbose_name='Convocatoria')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postulante', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Postulante',
                'verbose_name_plural': 'Postulantes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='DatosSocioeconomicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso_familiar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ingreso familiar mensual (COP)')),
                ('estrato', models.PositiveSmallIntegerField(choices=[(1, 'Estrato 1'), (2, 'Estrato 2'), (3, 'Estrato 3'), (4, 'Estrato 4'), (5, 'Estrato 5'), (6, 'Estrato 6')], verbose_name='Estrato socioeconómico')),
                ('num_hermanos_universidad', models.PositiveSmallIntegerField(default=0, verbose_name='Número de hermanos en universidad')),
                ('tipo_vivienda', models.CharField(choices=[('propia', 'Propia'), ('arrendada', 'Arrendada'), ('familiar', 'Familiar'), ('otro', 'Otro')], default='arrendada', max_length=20, verbose_name='Tipo de vivienda')),
                ('trabaja', models.BooleanField(default=False, verbose_name='¿Trabaja actualmente?')),
                ('numero_personas_hogar', models.PositiveSmallIntegerField(default=1, verbose_name='Número de personas en el hogar')),
                ('es_cabeza_hogar', models.BooleanField(default=False, verbose_name='¿Es cabeza de hogar?')),
                ('postulante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_socioeconomicos', to='postulantes.postulante', verbose_name='Postulante')),
            ],
            options={
                'verbose_name': 'Datos Socioeconómicos',
                'verbose_name_plural': 'Datos Socioeconómicos',
            },
        ),
        migrations.CreateModel(
            name='DatosAcademicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=200, verbose_name='Institución educativa')),
                ('carrera', models.CharField(max_length=200, verbose_name='Carrera')),
                ('semestre', models.PositiveSmallIntegerField(verbose_name='Semestre actual')),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Promedio acumulado (0-5)')),
                ('creditos_aprobados', models.PositiveIntegerField(verbose_name='Créditos aprobados')),
                ('creditos_totales', models.PositiveIntegerField(default=0, verbose_name='Créditos totales del programa')),
                ('postulante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_academicos', to='postulantes.postulante', verbose_name='Postulante')),
            ],
            options={
                'verbose_name': 'Datos Académicos',
                'verbose_name_plural': 'Datos Académicos',
            },
        ),
        migrations.AddIndex(
            model_name='postulante',
            index=models.Index(fields=['cedula'], name='postulantes_cedula_3fc8e1_idx'),
        ),
    ]
